### ISSUE TITLE
gem exec fails under Ruby 1.9

### ISSUE THREAD

**Issue by jakubpawlowicz** [wycats/bundler#146]
Executing 'gem exec script/console' under Ruby 1.9.1 (both p243 and p376) gives the following error:

  ERROR:  While executing gem ... (TypeError)
  can't convert Pathname into String

**Comment by luislavena** [comment]
Hello,

Will be very helpful you include the following information when reporting a bug:

The version of RubyGems used
The version of Bundler used
The version of Rails that you're trying to execute the console script
A pastie with the contents of Gemfile and your full platform information (under 1.9 doesn't say too much)

Also, since things are being executed inside RubyGems realm, execute the same command with `--debug -V` and pastie the full backtrace.

Thank you.

**Comment by jakubpawlowicz** [comment]
5 years and probably not relevant anymore.
