### ISSUE TITLE
Docs are vague

### ISSUE THREAD

**Issue by thewoolleyman** [wycats/bundler#40]
The following doc section is vague and inconsistent.  Please elaborate:

```
Yet another way is to manually require the environment file first. This is located in [bundle_path]/environments/default.rb. For example:

ruby -r vendor/gems/environment.rb my_ruby_script.rb
```

**Comment by wycats** [comment]
From trafficbroker:

<blockquote>I'm trying to bundle gems in a non-rails application. I'm unsure how this should be done.

I got as far as running 'gem bundle' locally and only sending the cache folder up to the server and requiring the environment.rb file before all other code.

The doc's seem to suggest that I need to run 'gem bundle --cached' on the remote machine in order to unpack the gems and build native extensions. Really? do I need rubygems and the bundler gem installed on the server? that seems to defy the point? How do I go about unpacking the gems on the server without using the gem command?

Any help would be greatly appreciated as I'm pretty confused by it all/</blockquote>

**Comment by wycats** [comment]
@thewoolleyman fixed

**Comment by wycats** [comment]
@trafficbroker wontfix -- rubygems and the bundler are a requirement for unbundling. They are not a runtime dependency.
