### ISSUE TITLE
Specify which ruby to use

### ISSUE THREAD

**Issue by namelessjon** [wycats/bundler#56]
It would be useful if there was a config option which would let you specify which ruby would be placed in the shabang line of installed scripts.  Installing small groups of gems for different rubies is most of the reason I use bundler, and not having to remember to invoke with '/path/to/ruby bin/foo' would be nice.

**Comment by atmos** [comment]
Yo,

Have you tried rvm?  It allows you to switch between different ruby versions easily and it wouldn't require any code changes.

**Comment by namelessjon** [comment]
I have.  I find it much less useful in a server setting, which is mostly where I use bundler.  I like having just one place I worry about my app's dependencies, not needing to make sure I keep the app itself and some remote rvm environment in sync.

Also, the one gem (SystemTimer) which actually prompted me to look at bundler is broken and apparently unneeded on 1.9, so it would mean code changes ...

**Comment by merbjedi** [comment]
rvm is awesome, but one thing I noticed is if I bundle using one ruby implementation, then switch to another ruby implementation, I get a seg fault when I try to run the app.

Is there an way to "rebundle" after I switch ruby implementations? The way I'm currently fixing things is to manually delete all the folders in gems (except the cache) then running "gem bundle" again

**Comment by HamptonMakes** [comment]
Actually, I have some code for this, merbjedi!

bundle_path("tmp/" + RUBY_RELEASE_DATE)

So, what that does is it does the unpacking in the tmp directory and also, puts it in a subdirectory named after the ruby release. This is good because really the gem builds should be temporary for that local install (don't have to git-ignore).

The next thing I want is to be able to specify where the cache is. This method means you can't use a cache!

**Comment by carllerche** [comment]
multi ruby support will be coming soon
