### ISSUE TITLE
deterministic source for a specific gem

### ISSUE THREAD

**Issue by merbjedi** [wycats/bundler#65]
Say I have several different gem sources defined in my Gemfile. 

```
source "http://gems.github.com"
source "http://gemcutter.org"
source "http://gems.merbjedi.com"
```

I need a way to say a specific gem (that may be contained on more than one source) should be retrieved from a specific source.

```
gem "haml", "2.1.0", :source => "http://gems.merbjedi.com"
```

or maybe something like this

```
source "http://gems.merbjedi.com" do
  gem "haml", "2.1.0"
end
```

**Comment by carllerche** [comment]
It checks sources in order that they are defined. If you are customizing gems so that they are different on various sources, you should a) vendor it b) release it on your own source with a different version or c) place your custom gem source at the top. If this does not solve your problems, please reopen the ticket and explain exactly why it did not.
